export enum Privileges {
  ACCESS = "ACCESS",
  CREATE = "CREATE",
  EXPORT = "EXPORT",
  APPROVE = "APPROVE",
  SEND_APPROVE = "SEND_APPROVE",
  COMPARE = "COMPARE",
  CLOSE = "CLOSE",
  INSERT = "INSERT",
  VIEWDETAILS = "VIEWDETAILS",
  DELETE = "DELETE",
  INSERTTRANS = "INSERTTRANS",
  TEMPLATE = "TEMPLATE",
  IMPORT = "IMPORT",
  RECORD = "RECORD",
  DELETETRANS = "DELETETRANS",
  EXECUTE = "EXECUTE",
  CANCEL = "CANCEL",
  REJECT = "REJECT",
  UPDATE = "UPDATE",
}

export enum Role {
  CHECKER = "checker",
  MAKER = "maker"
};
